// File generated by FlutterFire CLI.
// This file should always be included in your Flutter project.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZZJzsqxPD5C7Q2F62f5TYQhFBX5Zhpv4',
    appId: '1:820639614431:web:57b0a3e8576767d08ab06a',
    messagingSenderId: '820639614431',
    projectId: 'instawash-uganda',
    authDomain: 'instawash-uganda.firebaseapp.com',
    storageBucket: 'instawash-uganda.firebasestorage.app',
    measurementId: 'G-9PWJ92ZDVN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZZJzsqxPD5C7Q2F62f5TYQhFBX5Zhpv4',
    appId: '1:820639614431:android:8f7d8c5a4b9d2e1f3g4h5i',
    messagingSenderId: '820639614431',
    projectId: 'instawash-uganda',
    storageBucket: 'instawash-uganda.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZZJzsqxPD5C7Q2F62f5TYQhFBX5Zhpv4',
    appId: '1:820639614431:ios:a1b2c3d4e5f6g7h8i9j0k',
    messagingSenderId: '820639614431',
    projectId: 'instawash-uganda',
    storageBucket: 'instawash-uganda.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZZJzsqxPD5C7Q2F62f5TYQhFBX5Zhpv4',
    appId: '1:820639614431:macos:m1n2o3p4q5r6s7t8u9v0w',
    messagingSenderId: '820639614431',
    projectId: 'instawash-uganda',
    storageBucket: 'instawash-uganda.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZZJzsqxPD5C7Q2F62f5TYQhFBX5Zhpv4',
    appId: '1:820639614431:windows:w1x2y3z4a5b6c7d8e9f0g',
    messagingSenderId: '820639614431',
    projectId: 'instawash-uganda',
    storageBucket: 'instawash-uganda.firebasestorage.app',
  );
}
